apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-svc
  name: user-svc
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
        actorSystemName: user
    spec:
      containers:
        - name: user-svc
          image: user-svc:latest
          # remove for real clusters, useful for minikube
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /ready
              port: akka-management
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: "/alive"
              port: akka-management
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 20
          ports:
            - name: akka-remoting
              containerPort: 2552
              protocol: TCP
            # akka-management and bootstrap
            - name: akka-management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: grcp
              containerPort: 8010
              protocol: TCP
            - name: prometheus
              containerPort: 9080
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REQUIRED_CONTACT_POINT_NR
              value: "3"
            - name: CASSANDRA_SERVICE
              value: "cassandra"
            - name: KAFKA_SERVICE
              value: "kafka.kafka"
            - name: ELASTICSEARCH_URL
              value: "http://es-es-http:9200"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-svc
  name: user-svc
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
      nodePort: 30458
    - name: grpc
      protocol: TCP
      port: 8010
      targetPort: grpc
      nodePort: 30468
  selector:
    app: user-svc